### ISSUE TITLE
forestjs for Node.js

### ISSUE THREAD

**Issue by tvvignesh** [karpathy/forestjs#2]
Hi. Is there any way I can use this as a module for Node.js ? Thanks.

**Comment by cstavaru** [comment]
>           Hi. Is there any way I can use this as a module for Node.js ? Thanks.

Hello,

Just add the following line at the end of the randomforest.js file:

module.exports = forestjs;

Then in your NodeJS script (put the randomforest.js in the same folder as the script), use it like this:

var forestjs = require('./randomforest');
...
var mytree = new forestjs.RandomForest();
…
[call train/predict methods just like in the samples]

That's about it :)

**Comment by tvvignesh** [comment]
@cstavaru Hi. I forgot to say thanks :) I ended up using python for RandomForest (scikit) ultimately since I see a lot of community support there. Thanks again.
